### ISSUE TITLE
Please provide an example of a TestSpec to be able to test a route.

### ISSUE THREAD

**Issue by mayacr86** [NET-A-PORTER/spray-actor-per-request#2]
It has been very difficult for me to create a testSpec for a particular route. 
I would like to run something as simple as this (but don't know how, can't find any good reference):
 
    class MyRoutesTestSpec extends Specification with Specs2RouteTest with HttpService with MyRoute {
      "MyRoute" should {
        "return a 'HELLO' response for GET requests to /api/id/###" in {
          Get("/api/id/123") ~> routes ~> check {
            responseAs[String] === "HELLO"
          }
        }
    }

**Comment by ryanproud** [comment]
@mayacr86 Did you come up with a workaround to this?

**Comment by theon** [comment]
Hi,

I committed an quick example using scalatest in c9226b30c0f09e2f708cc09c641331265a2fb833. It should also work with specs2.

The only slightly ugly is overriding `petsWithOwner` to inject a TestProbe. It could be done nicer either by using a constructor argument for the `petsWithOwner` Props in RestRouting or by using the Cake Pattern

**Comment by ryanproud** [comment]
Awesome.  Thanks a lot.

**Comment by mayacr86** [comment]
great! thanks! :)
