### ISSUE TITLE
Pointless supervision strategy GetPetsWithOwnersActor

### ISSUE THREAD

**Issue by mkuthan** [NET-A-PORTER/spray-actor-per-request#4]
Hi Ian

Thanks for excellent blog post about actor per request strategy for spray app. 

Could you explain supervision strategy in GetPetsWithOwnersActor, please? GetPetsWithOwnersActor does not create any children actors for supervision.

**Comment by theon** [comment]
Good question! I don't think there is any reason for it and it should be removed.

**Comment by theon** [comment]
I have removed it now.

**Comment by mkuthan** [comment]
Thanks!
